In [ ]:
import sys
sys.path.append('../../../code/libs/')

%load_ext autoreload
%autoreload 2
import utils
import viz
import ios
import constants
import text as txtlib

In [2]:
import geopandas as gpd

In [3]:
files = ios.get_files_from_pattern("*2015_2022.csv")
files

['insurance_2015_2022.csv',
 'poverty_2015_2022.csv',
 'births_and_deaths_2015_2022.csv',
 'population_2015_2022.csv',
 'abortions_2015_2022.csv']

In [4]:
df_census = None
for fn in files:
    df = ios.read_csv(fn, index_col=['state_name','year'])
    df_census = df_census.join(df) if df_census is not None else df.copy()
df_census.shape

(408, 38)

In [5]:
df_census

,,insurance_any_coverage,insurance_uninsured,insurance_private,insurance_public,poverty_total,deaths_fetal,deaths_percent,births_total,births_percent,births_rate,...,years_55_to_59,years_60_to_64,years_65_to_69,years_70_to_74,years_75_to_79,years_80_to_84,years_85_and_above,pop_females_reproductive,abortions_by_location,abortions_by_residence
state_name,year,,,,,,,,,,,,,,,,,,,,,
Alabama,2015,4297.0,484.0,3198.0,1752.0,784,544.0,0.27,59657.0,0.09,12.28,...,6.8,6.2,5.0,3.6,2.7,1.9,1.7,45.2,5899.0,6618.0
Alaska,2015,607.0,106.0,478.0,205.0,65,58.0,0.03,11282.0,0.02,15.28,...,7.0,5.6,3.6,2.3,1.3,0.9,0.7,48.6,1334.0,1459.0
Arizona,2015,5991.0,728.0,4222.0,2586.0,1156,523.0,0.26,85351.0,0.13,12.50,...,6.1,5.7,5.0,3.9,2.8,1.9,1.8,45.0,12655.0,12644.0
Arkansas,2015,2647.0,278.0,1793.0,1231.0,475,248.0,0.12,38886.0,0.06,13.06,...,6.5,5.9,5.0,3.8,2.7,2.0,1.8,44.4,3771.0,3805.0
California,2015,35330.0,3317.0,24140.0,14670.0,5441,2465.0,1.23,491748.0,0.74,12.56,...,6.2,5.3,4.1,2.9,2.1,1.6,1.7,48.2,NaN,324.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virginia,2022,7901.0,545.0,6168.0,2888.0,704,497.0,0.25,95630.0,0.14,NaN,...,576469.0,543459.0,453677.0,365967.0,251265.0,158796.0,151301.0,1978555.0,16722.0,15600.0
Washington,2022,7199.0,468.0,5429.0,2786.0,696,421.0,0.21,83333.0,0.13,NaN,...,471024.0,484289.0,414287.0,336203.0,210852.0,130016.0,137582.0,1762040.0,20193.0,19463.0
West Virginia,2022,1638.0,103.0,1076.0,857.0,270,70.0,0.03,16929.0,0.03,NaN,...,120980.0,129971.0,121314.0,98411.0,65569.0,41634.0,39516.0,370780.0,831.0,1460.0
Wisconsin,2022,5529.0,303.0,4273.0,2079.0,386,320.0,0.16,60049.0,0.09,NaN,...,417692.0,411166.0,344952.0,273044.0,173751.0,118954.0,127919.0,1269088.0,3333.0,6378.0
Wyoming,2022,505.0,66.0,405.0,178.0,40,36.0,0.02,6049.0,0.01,NaN,...,36679.0,39149.0,36045.0,26768.0,17777.0,10552.0,9749.0,123813.0,540.0,764.0

In [6]:
gdf_shape = gpd.read_file('../../geo_boundaries/USA/us-state-boundaries.zip')
gdf_shape.head(5)

,gid,arealand,division,intptlat,name,objectid,areawater,intptlon,oid,funcstat,...,stusab,state,statens,centlat,basename,mtfcc,region,lsadc,geoid,geometry
0,16.0,278176477,0.0,18.217648,Puerto Rico,50.0,628200285,-66.410799,303146031,A,...,PR,72,01779808,18.216472,Puerto Rico,G4000,9.0,00,72,"MULTIPOLYGON (((-67.20794 18.44228, -67.21713 ..."
1,23.0,472276664,0.0,14.936784,Commonwealth of the Northern Mariana Islands,36.0,349301029,145.601021,-1625647860,A,...,MP,69,01779809,16.797438,Commonwealth of the Northern Mariana Islands,G4000,9.0,00,69,"MULTIPOLYGON (((145.57260 15.12502, 145.64831 ..."
2,31.0,1627312771,7.0,34.895526,Arkansas,44.0,-1334552525,-92.444626,266078934,A,...,AR,05,00068085,34.894021,Arkansas,G4000,3.0,00,05,"POLYGON ((-94.55218 36.10224, -94.58620 36.299..."
3,35.0,2136109036,5.0,38.647285,West Virginia,1.0,489848791,-80.618327,-1929409300,A,...,WV,54,01779805,38.641186,West Virginia,G4000,3.0,00,54,"POLYGON ((-81.74725 39.09538, -81.74385 39.102..."
4,40.0,-1616974352,1.0,41.597419,Rhode Island,6.0,1323457457,-71.527272,-1861167639,A,...,RI,44,01219835,41.594025,Rhode Island,G4000,1.0,00,44,"MULTIPOLYGON (((-71.78970 41.72456, -71.79788 ..."

In [7]:
df_census = df_census.reset_index()
df_census = df_census.merge(gdf_shape[['basename','stusab']], how='left', left_on='state_name', right_on='basename').drop(columns=['basename']).rename(columns={'stusab':'state_code'})
df_census

,state_name,year,insurance_any_coverage,insurance_uninsured,insurance_private,insurance_public,poverty_total,deaths_fetal,deaths_percent,births_total,...,years_60_to_64,years_65_to_69,years_70_to_74,years_75_to_79,years_80_to_84,years_85_and_above,pop_females_reproductive,abortions_by_location,abortions_by_residence,state_code
0,Alabama,2015,4297.0,484.0,3198.0,1752.0,784,544.0,0.27,59657.0,...,6.2,5.0,3.6,2.7,1.9,1.7,45.2,5899.0,6618.0,AL
1,Alaska,2015,607.0,106.0,478.0,205.0,65,58.0,0.03,11282.0,...,5.6,3.6,2.3,1.3,0.9,0.7,48.6,1334.0,1459.0,AK
2,Arizona,2015,5991.0,728.0,4222.0,2586.0,1156,523.0,0.26,85351.0,...,5.7,5.0,3.9,2.8,1.9,1.8,45.0,12655.0,12644.0,AZ
3,Arkansas,2015,2647.0,278.0,1793.0,1231.0,475,248.0,0.12,38886.0,...,5.9,5.0,3.8,2.7,2.0,1.8,44.4,3771.0,3805.0,AR
4,California,2015,35330.0,3317.0,24140.0,14670.0,5441,2465.0,1.23,491748.0,...,5.3,4.1,2.9,2.1,1.6,1.7,48.2,NaN,324.0,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,Virginia,2022,7901.0,545.0,6168.0,2888.0,704,497.0,0.25,95630.0,...,543459.0,453677.0,365967.0,251265.0,158796.0,151301.0,1978555.0,16722.0,15600.0,VA
404,Washington,2022,7199.0,468.0,5429.0,2786.0,696,421.0,0.21,83333.0,...,484289.0,414287.0,336203.0,210852.0,130016.0,137582.0,1762040.0,20193.0,19463.0,WA
405,West Virginia,2022,1638.0,103.0,1076.0,857.0,270,70.0,0.03,16929.0,...,129971.0,121314.0,98411.0,65569.0,41634.0,39516.0,370780.0,831.0,1460.0,WV
406,Wisconsin,2022,5529.0,303.0,4273.0,2079.0,386,320.0,0.16,60049.0,...,411166.0,344952.0,273044.0,173751.0,118954.0,127919.0,1269088.0,3333.0,6378.0,WI
407,Wyoming,2022,505.0,66.0,405.0,178.0,40,36.0,0.02,6049.0,...,39149.0,36045.0,26768.0,17777.0,10552.0,9749.0,123813.0,540.0,764.0,WY

In [8]:
df_census.head(5)

,state_name,year,insurance_any_coverage,insurance_uninsured,insurance_private,insurance_public,poverty_total,deaths_fetal,deaths_percent,births_total,...,years_60_to_64,years_65_to_69,years_70_to_74,years_75_to_79,years_80_to_84,years_85_and_above,pop_females_reproductive,abortions_by_location,abortions_by_residence,state_code
0,Alabama,2015,4297.0,484.0,3198.0,1752.0,784,544.0,0.27,59657.0,...,6.2,5.0,3.6,2.7,1.9,1.7,45.2,5899.0,6618.0,AL
1,Alaska,2015,607.0,106.0,478.0,205.0,65,58.0,0.03,11282.0,...,5.6,3.6,2.3,1.3,0.9,0.7,48.6,1334.0,1459.0,AK
2,Arizona,2015,5991.0,728.0,4222.0,2586.0,1156,523.0,0.26,85351.0,...,5.7,5.0,3.9,2.8,1.9,1.8,45.0,12655.0,12644.0,AZ
3,Arkansas,2015,2647.0,278.0,1793.0,1231.0,475,248.0,0.12,38886.0,...,5.9,5.0,3.8,2.7,2.0,1.8,44.4,3771.0,3805.0,AR
4,California,2015,35330.0,3317.0,24140.0,14670.0,5441,2465.0,1.23,491748.0,...,5.3,4.1,2.9,2.1,1.6,1.7,48.2,NaN,324.0,CA

In [9]:
fcols = ['state_name','state_code','year']
lcols = sorted(list(set(df_census.columns) - set(fcols)))

df_census = df_census[fcols + lcols]
df_census

,state_name,state_code,year,abortions_by_location,abortions_by_residence,births_avg_age_mother,births_avg_weight,births_percent,births_rate,births_total,...,years_50_to_54,years_55_to_59,years_5_to_9,years_60_to_64,years_65_to_69,years_70_to_74,years_75_to_79,years_80_to_84,years_85_and_above,years_under_5
0,Alabama,AL,2015,5899.0,6618.0,27.03,3197.72,0.09,12.28,59657.0,...,7.1,6.8,6.3,6.2,5.0,3.6,2.7,1.9,1.7,6.1
1,Alaska,AK,2015,1334.0,1459.0,27.94,3401.84,0.02,15.28,11282.0,...,7.2,7.0,7.0,5.6,3.6,2.3,1.3,0.9,0.7,7.5
2,Arizona,AZ,2015,12655.0,12644.0,27.92,3289.47,0.13,12.50,85351.0,...,6.5,6.1,6.9,5.7,5.0,3.9,2.8,1.9,1.8,6.5
3,Arkansas,AR,2015,3771.0,3805.0,26.64,3233.52,0.06,13.06,38886.0,...,6.8,6.5,6.8,5.9,5.0,3.8,2.7,2.0,1.8,6.5
4,California,CA,2015,NaN,324.0,29.43,3290.40,0.74,12.56,491748.0,...,6.9,6.2,6.6,5.3,4.1,2.9,2.1,1.6,1.7,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,Virginia,VA,2022,16722.0,15600.0,30.02,3259.60,0.14,NaN,95630.0,...,561174.0,576469.0,511965.0,543459.0,453677.0,365967.0,251265.0,158796.0,151301.0,494148.0
404,Washington,WA,2022,20193.0,19463.0,30.24,3318.89,0.13,NaN,83333.0,...,466904.0,471024.0,465882.0,484289.0,414287.0,336203.0,210852.0,130016.0,137582.0,440172.0
405,West Virginia,WV,2022,831.0,1460.0,27.53,3217.69,0.03,NaN,16929.0,...,116126.0,120980.0,98563.0,129971.0,121314.0,98411.0,65569.0,41634.0,39516.0,90380.0
406,Wisconsin,WI,2022,3333.0,6378.0,29.63,3290.28,0.09,NaN,60049.0,...,374189.0,417692.0,345769.0,411166.0,344952.0,273044.0,173751.0,118954.0,127919.0,321594.0
407,Wyoming,WY,2022,540.0,764.0,28.37,3165.51,0.01,NaN,6049.0,...,32599.0,36679.0,36989.0,39149.0,36045.0,26768.0,17777.0,10552.0,9749.0,32789.0

In [10]:
FN_FINAL = 'USA_all_census_stats.csv'
ios.save_csv(df_census.reset_index(), FN_FINAL)